---
- name: Configure system
  hosts: webservers
  become: true
  roles:
    - common
    - wireguard
    - docker
    - node_exporter
    - prometheus
    - grafana
    - loki
    - promtail
    - webserver
